DROP PROCEDURE IF EXISTS ADD_REFEREE_COLUMN_IN_MATCH;
CREATE PROCEDURE ADD_REFEREE_COLUMN_IN_MATCH()
    language plpgsql
as $$
BEGIN
ALTER TABLE match
    ADD COLUMN IF NOT EXISTS referee_id int ;
END $$;
CALL ADD_REFEREE_COLUMN_IN_MATCH();
DROP PROCEDURE ADD_REFEREE_COLUMN_IN_MATCH;

ALTER TABLE match
ADD FOREIGN KEY (referee_id) REFERENCES users(id);