--Set default score 0 for players

DROP PROCEDURE IF EXISTS SET_SCORE_DEFAULT_0_FOR_PLAYERS;
CREATE PROCEDURE SET_SCORE_DEFAULT_0_FOR_PLAYERS()
language plpgsql
as $$
BEGIN
  ALTER TABLE tournament_user ALTER COLUMN score SET DEFAULT 0;
END $$;
CALL SET_SCORE_DEFAULT_0_FOR_PLAYERS();
DROP PROCEDURE SET_SCORE_DEFAULT_0_FOR_PLAYERS;