-- Add current_round_number column to tournament table

DROP PROCEDURE IF EXISTS ADD_CURRENT_ROUND_ID_TO_TOURNAMENT;
CREATE PROCEDURE ADD_CURRENT_ROUND_ID_TO_TOURNAMENT()
    language plpgsql
as $$
BEGIN
ALTER TABLE tournament
ADD COLUMN current_round_id int;
END $$;
CALL ADD_CURRENT_ROUND_ID_TO_TOURNAMENT();
DROP PROCEDURE ADD_CURRENT_ROUND_ID_TO_TOURNAMENT;