-- Add state column in round table

DROP PROCEDURE IF EXISTS ADD_STATE_COLUMN_TO_ROUND;
CREATE PROCEDURE ADD_STATE_COLUMN_TO_ROUND()
    language plpgsql
as $$
BEGIN
ALTER TABLE round
    ADD COLUMN state varchar(10);
END $$;
CALL ADD_STATE_COLUMN_TO_ROUND();
DROP PROCEDURE ADD_STATE_COLUMN_TO_ROUND;