-- Add registration_open and max_participants_no columns in tournament table

DROP PROCEDURE IF EXISTS ADD_REGISTRATION_AND_PARTICIPANTS_TO_TOURNAMENT;
CREATE PROCEDURE ADD_REGISTRATION_AND_PARTICIPANTS_TO_TOURNAMENT()
    language plpgsql
as $$
BEGIN
ALTER TABLE tournament
    ADD COLUMN registration_open boolean NOT NULL,
    ADD COLUMN max_participants_no int NOT NULL;
END $$;
CALL ADD_REGISTRATION_AND_PARTICIPANTS_TO_TOURNAMENT();
DROP PROCEDURE ADD_REGISTRATION_AND_PARTICIPANTS_TO_TOURNAMENT;